#! /usr/bin/env python3
# This setup the applications for shift start

import os
import time
import webbrowser

os.chdir(br'C:\Users\Desktop\MyScripts')

# delete Internet Explorer in User Pinned
pinnedTab = br'C:\Users\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\Internet Explorer.lnk'
try:
    os.unlink(pinnedTab)
except OSError:
    pass

# opens Default App window and closes *.exe
with open('cmd.txt') as cmd:
    cmds = cmd.read().splitlines()
for cmd in cmds:
    try:
        os.system(cmd)
    except OSError:
        pass

# opens work App separately
with open('app.txt') as f:
    apps = f.read().splitlines()
for app in apps:
    os.startfile(app, 'open')

time.sleep(10) #wait for 10 seconds

# Opens favorite url to start shift
with open('urls.txt') as f2:
    urls = f2.read().splitlines()
for url in urls:
    webbrowser.open(url)
